### ISSUE TITLE
Next Due API Issue

### ISSUE THREAD

**Issue by W-S-D1** [TomFrankly/pipedream-notion-recurring-tasks#10]
I get this message: "Your chosen Target Database does not contain a Next Due API formula property. This workflow requires this property to function. If you have renamed it in your database, please set it in the Next Due API Property field below. If your database doesn't contain it, please use one of the templates listed in the "Compatibility" section in the instructions above."

It won't let me choose anything in the "Next Due API Property" dropdown.
![000](https://github.com/TomFrankly/pipedream-notion-recurring-tasks/assets/167393264/4e9a7817-c426-4a00-81af-30659a7ebb43)

**Comment by TomFrankly** [comment]
@W-S-D1 this means your chosen database doesn't have the "Next Due API" property in it.

I'd recommend using one of my templates for this automation, but you can add the property to your own database using this guide: https://thomasjfrank.com/notion-automated-recurring-tasks/#formulas-and-properties
