### ISSUE TITLE
Next Due API Issue for Ultimate Tasks

### ISSUE THREAD

**Issue by moviedrummer** [TomFrankly/pipedream-notion-recurring-tasks#11]
I'm using the ultimate tasks database provided that uses the same next due function. To my knowledge, nothing was tampered with for that or related properties to mess it up, but like in a previous post, I'm getting the error saying I don't have the next due api property. 

![image](https://github.com/TomFrankly/pipedream-notion-recurring-tasks/assets/167485447/6139e62d-ce96-4a8b-83f6-33519a9e0b9c)

**Comment by TomFrankly** [comment]
@moviedrummer you might have an older version of Ultimate Tasks, duplicated before we updated it to include that propety.

You can add it to your copy using this reference: https://thomasjfrank.com/notion-automated-recurring-tasks/#formulas-and-properties
