### ISSUE TITLE
APIResponseError

### ISSUE THREAD

**Issue by HLoots** [TomFrankly/pipedream-notion-recurring-tasks#13]
Hello, 
I have always loved all these fancy automations you have put out. This is the first time I have encountered an issue with any of your coding yet it is the simplest! 

Here is the error I am receiving: 

<img width="540" alt="Screenshot 2024-05-01 at 12 13 42 PM" src="https://github.com/TomFrankly/pipedream-notion-recurring-tasks/assets/168662830/3fb54eb6-e5a8-45be-829f-9aa8db663361">

I have deleted the project and restarted fresh.

Any input for help is greatly appreciated.

**Comment by TomFrankly** [comment]
Hi @HLoots! 

Does that error message go more to the right? It looks like it might be cut off. Usually, the end of each line will note the code line where the error occurred. That'd be helpful to see.

My guess is that one of your database properties is causing an issue with the automation, though it's hard to tell which. It's likely a formula property.

**Comment by TomFrankly** [comment]
Also, does this happen when you test the workflow, during a normal scheduled run, or when you're setting the properties prior to testing?

**Comment by HLoots** [comment]
I just found the fix myself. I had two properties named differently than the original in the video. 

Instead of Recur Interval, I had Recurring Interval and the same with Recur Unit, I had Recurring Unit. All seems good to go now!
