### ISSUE TITLE
Bug: Cannot read properties of undefined (reading 'iso8601')

### ISSUE THREAD

**Issue by Xytronix** [TomFrankly/pipedream-notion-recurring-tasks#14]
I do get the following error while setting up the properties prior to testing

```
Cannot read properties of undefined (reading 'iso8601')

at Object.run (file:///tmp/__pdg__/dist/code/f1a18e75fe918398e71565d5f747a71993c0ac9a8d42a15bedf84624bc136ffd/component.mjs:937:49)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at null.executeComponent (/var/task/launch_worker.js:288:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:788:28)
```

**Comment by TomFrankly** [comment]
Hi @Xytronix ,

Did you test your Trigger step? If you did, that iso8601 object should exist. This error message indicates that it doesn't, which should only happen if the trigger step wasn't tested.

![CleanShot 2024-05-13 at 09 56 23@2x](https://github.com/TomFrankly/pipedream-notion-recurring-tasks/assets/684961/679c6113-477f-4088-891c-77a37c66ff06)

**Comment by Xytronix** [comment]
Yep, I tested the trigger step and the error went away.

However, I experienced a different problem. All tasks went unchecked, despite not recurring, and the Type formula was replaced.

`if(empty(prop("Recur Interval")), "⏳One-Time", "⏳One-Time")`

**Comment by TomFrankly** [comment]
@Xytronix the Type property should indeed be replaced with that top formula. It's confusing for sure, but it needs to happen – that bottom version of Type is only useful for people who are doing the "manual" version of recurring task processing. It simply keeps tasks from leaving task views if "Done" is checked.

But when we do automated processing with this script, you want those tasks to leave until they're unchecked again.

As for all taks going unchecked – that shouldn't happen. You can see in the code that this script will only pull tasks where the Next Due API property is not the "∅" symbol: https://github.com/TomFrankly/pipedream-notion-recurring-tasks/blob/main/notion-recurring-tasks.mjs#L673C30-L673C30

And by default, tasks without a Recur Interval will have that symbol. If they don't, then there may be something wrong with your properties. If you're not using one of my up-to-date templates, you can find the correct formulas in the first toggle here: https://thomasjfrank.com/notion-automated-recurring-tasks/#faqs-and-reference-guides

**Comment by Xytronix** [comment]
I got to the root of the problem. When a due date is set for a non-recurring task, pipedream will update it. Whether it was from the past or is in the future. Such a scenario wasn't considered for the Next Due API property.

**Comment by TomFrankly** [comment]
@Xytronix can you share a screen recording at all? That shouldn't happen, and has never happened for me, and I have plenty of non-recurring tasks with due dates. I've never seen this reported by any other user, either.

The Pipedream automation only queries your Notion database for finished recurring tasks. The query filter in the code looks both for a "Done" status, as well as for a Next Due API value that isn't "∅". And any task that doesn't have a Recur Interval set should have "∅" as its Next Due API value.

For example, this task in my tasks database has a due date, but no recur interval:

![CleanShot 2024-05-14 at 09 35 36@2x](https://github.com/TomFrankly/pipedream-notion-recurring-tasks/assets/684961/db585c62-6973-4ad0-bdfc-1743c5aaa19f)

As a result, the Next Due API value is "∅", and thus it doesn't get processed by Pipedream.

![CleanShot 2024-05-14 at 09 36 13@2x](https://github.com/TomFrankly/pipedream-notion-recurring-tasks/assets/684961/79e55b58-a69f-43e6-81d5-f952e4d0f0ea)

**Comment by Xytronix** [comment]
Issue resolved, there was an issue with wrong linked property names. Sorry for the inconvenience.
