### ISSUE TITLE
TypeError Cannot read properties of undefined (reading 'event')

### ISSUE THREAD

**Issue by adelehuu** [TomFrankly/pipedream-notion-recurring-tasks#17]
Encountered this error when running the test after setting up the task tracker:

```
TypeError
Cannot read properties of undefined (reading 'event')

DETAILS
    at Object.run (file:///tmp/__pdg__/dist/code/f1a18e75fe918398e71565d5f747a71993c0ac9a8d42a15bedf84624bc136ffd/component.mjs:937:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at null.executeComponent (/var/task/launch_worker.js:288:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:788:28)
```

I saw ticket #14 on "Cannot read properties of undefined" where you suggested to test the trigger event. I have tested trigger event but still get the above error.

What should I do?

**Comment by TomFrankly** [comment]
Hi @adelehuu, could you post a Loom recording or screenshots showing the details?

**Comment by adelehuu** [comment]
Hi @TomFrankly thanks for replying. Here's a Loom recording of what's going on. I realized that I have this error even with the Recurring Tasks template you kindly provided, and I'm using the template here to run this. I get the same error when I run it with my own setup...

https://www.loom.com/share/1f1d6fed116e4c1fa82c852c8234822b?sid=6af2e68a-d0ef-4dc6-8010-6e0c557195a2

Please let me know if you have any thoughts on how to solve this...

Thanks!!

**Comment by TomFrankly** [comment]
@adelehuu found the problem!

This property should have been auto-filled with the value `{{steps}}` – that's how steps in Pipedream are able to reference values from other steps.

When you used my template, did it not automatically bring that value in?

![CleanShot 2024-06-08 at 08 19 19@2x](https://github.com/TomFrankly/pipedream-notion-recurring-tasks/assets/684961/59d1ae7c-2933-4ade-8170-4b467933cf75)

**Comment by adelehuu** [comment]
@TomFrankly that's a very good point that you caught. Keen eye!

Hmm, so it does not seem to auto-fill, is there a manual fill that I should put in? or wondering if you have any suggestions on what I may have changed to make the auto-fill disappear? Maybe I could change it back...

Thanks so much for the efficient trouble-shooting!

**Comment by TomFrankly** [comment]
It's odd that it wasn't auto-filled for you - I tested the workflow link this morning and it was there for me.

In any case, all you need to do is type {{steps}} in that field with the curly braces!
