### ISSUE TITLE
APIResponseError

### ISSUE THREAD

**Issue by sadsantan** [TomFrankly/pipedream-notion-recurring-tasks#20]
I keep getting this error when testing the automation
![Screenshot 2024-09-02 112356](https://github.com/user-attachments/assets/cc370ea1-bb27-4218-bc67-7ba1d527d1b5)
![Screenshot 2024-09-02 112507](https://github.com/user-attachments/assets/e6f891a5-9003-45e5-9d7f-166a811509c2)

**Comment by sadsantan** [comment]
I think I figured it out. "Next Due API" wasn't properly defined
![Screenshot 2024-09-02 153641](https://github.com/user-attachments/assets/d6131fcb-3003-4261-8d38-3ef8a2383d36)

**Comment by TomFrankly** [comment]
Glad you got it figured out!
