### ISSUE TITLE
The automation shouldn't update the very same recurring task that was completed, it should make a copy of it instead

### ISSUE THREAD

**Issue by JunDevl** [TomFrankly/pipedream-notion-recurring-tasks#23]
What i mean is, all the automation does is update a recurring task that was completed by changing its due value to next due and unmarking the completion checkbox property (or status property if you're going that path). Why is that though? Why not just create a copy of said task and instead modify only the copy?

Simply updating the same recurring task by changing its date and completion status, you basically inhibits task tracking, so if a task is set to recurring, it'll be impossible for you to track when that task was completed and, therefore, control what tasks you're doing or not or see how much time you spent in a certain task.

I know this is a small thing, but currently we're basically incentivized to not use recurring tasks at all in our workflow, since we won't be able to include them anyway in our study planning or whatever.

**Comment by TomFrankly** [comment]
@JunDevl correct, that's what this automation does. It follows the pattern most other task management apps use. For example, if you check off a recurring task in Todoist, it simply moves the date on that task. You won't see the same task in the Completed list.

If you want to add some tracking, you could add another step to the PIpedream automation that adds a bullet list item block to the page body with the date of the last time you checked it off, though.
