### ISSUE TITLE
Secondary Task Status Property - Not showing

### ISSUE THREAD

**Issue by RemyMachado** [TomFrankly/pipedream-notion-recurring-tasks#4]
Hey,

I'm having an issue during the Pipedream recurring task configuration. When I try to add the `Kanban status` as the secondary prop, it's not showing in the list of options. I'm only left with the `done` property option to choose:

![image](https://github.com/TomFrankly/pipedream-notion-recurring-tasks/assets/30229752/d607d230-d7e7-487c-b992-42fabc702341)

Note that I didn't edit the database, I didn't even unlock the `All Tasks [UB]` DB. :thinking: 
Here's the property in the `Task with Sub-Tasks` template, should I edit something to make it appear in the Pipedream interface? It may be due to my template version becoming old.

![image](https://github.com/TomFrankly/pipedream-notion-recurring-tasks/assets/30229752/661e6465-8365-4822-bc1d-846a8e557111)

**Comment by TomFrankly** [comment]
@RemyMachado yep, it's because your Kanban Status is a **Select** property. If you convert it to a **Status** property, it'll show up!

I've tested this; you can convert that property to Status-type without any ill effects to your template.
