### ISSUE TITLE
Something is wrong with The Pipedream Workflow 

### ISSUE THREAD

**Issue by MidnightPremic** [TomFrankly/pipedream-notion-recurring-tasks#7]
I've been trying to automate the recurring tasks workflow with pipedream. But i've been getting these errors.

![Screen Shot 2024-04-16 at 7 15 45 PM](https://github.com/TomFrankly/pipedream-notion-recurring-tasks/assets/167269925/3bcad51c-554d-4072-9992-031e6a199e4e)

**This shows up under the test logs in the project:**⬇️ 
at null.buildRequestError (/tmp/__pdg__/dist/code/788a1de22ecc007b6904dab5d7c9de8e7365d5484c93ce59a7691596a15f4064/node_modules/.pnpm/@notionhq+client@2.2.15/node_modules/@notionhq/client/build/src/errors.js:162:16)
    at Client.request (/tmp/__pdg__/dist/code/788a1de22ecc007b6904dab5d7c9de8e7365d5484c93ce59a7691596a15f4064/node_modules/.pnpm/@notionhq+client@2.2.15/node_modules/@notionhq/client/build/src/Client.js:378:54)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by TomFrankly** [comment]
@MidnightPremic looks like the Notion API is throwing a validation error. Can you open the toggles and show me the full error messages from those last two lines?

![CleanShot 2024-04-17 at 07 56 09@2x](https://github.com/TomFrankly/pipedream-notion-recurring-tasks/assets/684961/424ed47c-91d0-4a5c-b622-5da9ab080f74)

**Comment by MidnightPremic** [comment]
> @MidnightPremic looks like the Notion API is throwing a validation error. Can you open the toggles and show me the full error messages from those last two lines?
> 
> ![CleanShot 2024-04-17 at 07 56 09@2x](https://private-user-images.githubusercontent.com/684961/323245747-424ed47c-91d0-4a5c-b622-5da9ab080f74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNzMyODUsIm5iZiI6MTcxMzM3Mjk4NSwicGF0aCI6Ii82ODQ5NjEvMzIzMjQ1NzQ3LTQyNGVkNDdjLTkxZDAtNGE1Yy1iNjIyLTVkYTlhYjA4MGY3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QxNjU2MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yN2FkNTZhMTY2YmVkZDhlYjllYjcyMzI1MmY5YzAxZDZhM2E4MjM5OTE3Y2MxZDBmMTc2MmJiYmI4MDMzNGFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iJp5aWwMbeEpso-E9QVz5vSxPWHMdulhQgjBnsoOrS0)

Here are The 2 Toggles of The Error Message:
![Screen Shot 2024-04-17 at 9 58 16 AM](https://github.com/TomFrankly/pipedream-notion-recurring-tasks/assets/167269925/ba549cf0-10f3-41c5-8eea-d3eee7d01e80)
![Screen Shot 2024-04-17 at 9 58 24 AM](https://github.com/TomFrankly/pipedream-notion-recurring-tasks/assets/167269925/6f6cd221-ff59-4d1d-b7f1-8126d9accf18)

**Comment by TomFrankly** [comment]
@MidnightPremic are you using one of my templates? If so, did you change any of the property names?

I believe the problem is either with the UTC Offset formula or the Type formula.

I'd recommend making sure those properties exist, are named with those exact names, and contain the formula code in this reference: https://thomasjfrank.com/notion-automated-recurring-tasks/#formulas-and-properties

Once that's done, if you're still getting an error, try re-generating the workflow from my link again to ensure its up to date: https://thomasjfrank.com/notion-automated-recurring-tasks/#automated-recurring-tasks-pipedream-workflow
