### ISSUE TITLE
Can't launch automation (wrong date format?)

### ISSUE THREAD

**Issue by marcinhinz84** [TomFrankly/pipedream-notion-recurring-tasks#8]
Error appear when trying to final test automation. Same error appear at night when automation runs.
I'm based in Poland but Notion is in English.
All columns seems to have proper names.
I didn't change date format.

During configuration I also couldn't use second "done" state because kanban statuses didn't show as an option to choose.
But there were additional dropdown menu at the end of configuratoin screen in pipedream. I had to choose column for (i think) "Next due date".

_"Your workflow generated the following error at 9:57:00 PM GMT on Tue, Apr 16, 2024:

SyntaxError — Unexpected token 'A', "April 19, 2024" is not valid JSON

See https://pipedream.com/@marcinhinz/event-history/2fCUayZyoIEDnzcEcdPLDUD3Z9n for details on the error and the associated logs.

Questions or feedback? Check out the docs at https://pipedream.com/docs, or join our community at https://pipedream.com/support."_

![Screenshot of Notion at 17 Apr 2024 at 07_14_07](https://github.com/TomFrankly/pipedream-notion-recurring-tasks/assets/13133236/41562d2c-6cad-4499-8cd5-3ed5859342e7)

**Comment by TomFrankly** [comment]
@marcinhinz84 did your copy of the workflow ask you to set a Next Due API property value? If so, did you chose "Next Due" for that value?

Note that Next Due API is a separate property. If your template doesn't have it, you can add it – check out the 07:19 timestamp in the video here: https://thomasjfrank.com/notion-automated-recurring-tasks/#formulas-and-properties

**Comment by marcinhinz84** [comment]
During configuration Pipedream asked me about "next due api" and I choosen "Next Due" (I took fresh copy of "Ultimate task" free version for this experiment).
I think that I know where is the problem (can't check it right now): pipedream asked about "next due...." and I don't have "Next Due API" in my task database (Just "Next Due" column).

**Comment by TomFrankly** [comment]
@marcinhinz84 I just checked - Ultimate Tasks does have the Next Due API property. Perhaps you got your new copy from an unofficial source?

Here's the link: https://thomasfrank.notion.site/Ultimate-Tasks-for-Notion-982c5dd2b2c24818b58bf5f4f8f04071?pvs=4

**Comment by marcinhinz84** [comment]
@TomFrankly I'm 100% sure that template was from your library. I re-sub to your email list and downloaded it with a very first link.
Now got the new one (mentioned by you above) and see that it looks different and even have different icon.
Maybe there is a link to older version in one of the email automation?

<img width="231" alt="Screenshot of Notion at 18 Apr 2024 at 16_18_24" src="https://github.com/TomFrankly/pipedream-notion-recurring-tasks/assets/13133236/26d6519d-ba6c-4862-b649-70914ddc9248">

**Comment by marcinhinz84** [comment]
Hmmmmm I see that subscribe confirmation comes from collegeinfogeek.com domain.
Maybe you were correct that source was bad.

**Comment by TomFrankly** [comment]
@marcinhinz84 ah, collegeinfogeek.com is correct! That was my first website, which I ran for many years (it's still online). The transition to making Notion templates was super gradual, and my entire email list was already in the collegeinfogeek.com Convertkit account. So just kept using that.

I think my email auto-responder must be linking to an old version of Ultimate Tasks. Thanks for catching that!

**Comment by marcinhinz84** [comment]
@TomFrankly ok, with the new version the whole process worked seamless :)
So the problem was in totally different place - old template.

Thanks Tom! I'm happy that I helped too ;)
